### ISSUE TITLE
C++Builder compatibility problem

### ISSUE THREAD

**Issue by MaxTerentiev** [d-mozulyov/UniConv#1]
UniConv can't be used in C++Builder because TUniConvContext is of type 'object' - it's cannot be translated to c++ .hpp file.

Please can you change them from Object to Record or Class to make it compatible with c++builder ?

**Comment by d-mozulyov** [comment]
It looks like to implement compatibility in C++ Buuilder, we should use the [$HPPEMIT](http://docwiki.embarcadero.com/RADStudio/Tokyo/en/HPP_emit_(Delphi)) directive and mark the TUniConvContext type as a class. I would be grateful if you fix this problem and send me a pull request.

**Comment by d-mozulyov** [comment]
Fixed
