### ISSUE TITLE
Strange comparison of the range

### ISSUE THREAD

**Issue by wyfinger** [d-mozulyov/UniConv#3]
https://github.com/d-mozulyov/UniConv/blob/f9a7142610eb5afb0d7584bf636b46a1e2157018/sources/UniConv.pas#L12368

**Comment by d-mozulyov** [comment]
Yep, it looks like "if (S1 in [$21..$28, $30..$74]) then" should be used. But it need to be tested. The original code was taken from libiconv library, cp932_mbtowc function

**Comment by d-mozulyov** [comment]
Fixed
